### ISSUE TITLE
Expand notification for shortlisted proposals

### ISSUE THREAD

**Issue by hktang** [hktang/apnis#108]

**Comment by browncrowned** [comment]
Dear XXX,
Congratulations for passing the Stage One Review! This is to inform you that your Summary Proposal **Proposal Reference Number** has been shortlisted for Stage Two: Full Proposal Submission. 

Please note that in order for us to consider your proposal at the next stage of the review process, Stage Two, we now require you to submit a **mandatory Full Proposal**. **Please log in to APNIS and complete your full proposal online.** 

Please carefully follow the guidelines for proposal submission ensuring that all sections are addressed in full and in an orderly manner. You can find the guide for proponent on the left sidebar of the form page. 
 
You should also **consider the comments & suggestions from reviewers** listed in a pdf document on the left sidebar when devising your full proposal. Please note that the deadline for receiving your Full Proposal is **Wednesday, 14 February 2018 – midnight, Japanese Standard Time. Note that the system will automatically shut down at 23.59, therefore please ensure that you submit the full proposal before that.** 

If you find any difficulties or issues regarding the full proposal submission, please contact us right away. Thank you very much and best of luck!

**Comment by browncrowned** [comment]
What do you think?

**Comment by hktang** [comment]
looks good! let's use this as a template, but also allow customization; 

- [ ] add template
- [ ] add "test send" to admin

**Comment by browncrowned** [comment]
Hi @hktang , there is an inquiry from a collaborator. So, the proponent may not have access to email during the time when the notification is sent to the proponent. The collaborator asked that notification to be sent to his email. Do you think this is possible? It's supposed to be automatic, no? Or I can just forward the notification copied to my email to that person?

**Comment by hktang** [comment]
I see....

We can only ensure that the notification is carbon copied to any email addresses contained in the "collaborators" box. This is assuming proponents have filled the collaborator information correctly (which is enforced only in Stage 2; in Stage 1, collaborator box is "free input"). 

In stage 2, we can have the system send emails to carbon copy all collaborators.

**Comment by browncrowned** [comment]
Exactly, the summary proposal, it's only the big box and they can write freely. So, I am not sure how to extract the email and include in the notification mailing list?

**Comment by hktang** [comment]
This is doable with "regular expressions". Let's add that as a feature?

As mentioned, the only downside is that some proponents might not have included proponent emails in that box -- in this case, no emails will be sent to collabs .. 

- [ ] Notify all collaborators mentioned in the summary proposal.

**Comment by browncrowned** [comment]
Okay, I think it's okay. If they don't provide the email, then it's their fault :D
