### ISSUE TITLE
Guidelines for full proposal form

### ISSUE THREAD

**Issue by hktang** [hktang/apnis#110]

**Comment by browncrowned** [comment]
need to be visible on the form page.

**Comment by hktang** [comment]
Would it be a PDF containing the guidedance, or do we use the same style as SP forms, i.e. a short text under each box? 

Also not quite sure about its relation with the guide as mentioned in  #123. Let's do tachikaigi..

**Comment by browncrowned** [comment]
Hmm..guidelines is already available since summary proposal actually. the CRRP guide for proponents. So, I think just need to update that one (the pdf one). The other can be the same style as SP form, since they are expanding from SP anyways.

**Comment by browncrowned** [comment]
@hktang lets try the following:
1. Introduction
Description of the proposed project (3,000 characters)
Concise literature review (3,000 characters)
Relevance to APN Strategic Plan (3,000 characters)

2. Objectives and deliverables
Objectives of the proposed project (1,500 characters)
Expected deliverables/outputs (1,500 characters)

3. Project methodology and work plan
Description of the project methodology (15,000 characters)
Project work plan and timeline (2,500 characters)

4. Budget
Concise budget plan (1,500 characters)
Administrative support, in-kind and co-funding consideration (1,500 characters)

5. Relevance to global change and sustainability
Relevance to policy processes and sustainability (1,500 characters)
Relevance to scientific capacity development for global change research (1,500 characters)
Relationship with global change programmes and networks (1,500 characters)
Related research works (2,500 characters)

6. Data management and data sharing plan (3,500 characters)

7. Communications and publications (3,500 characters)

**Comment by hktang** [comment]
Looks good!

**Comment by hktang** [comment]
Validation added by 2c94f23270d6afbeeb7243562fd7e8ba6d0bc158
