### ISSUE TITLE
Separate upload box for images under methodlogy

### ISSUE THREAD

**Issue by hktang** [hktang/apnis#111]

**Comment by browncrowned** [comment]
I am thinking about adding pictures in line with text like in googlemail. So, formula, figure, diagram, all should be in picture format and then proponents can paste it into the form box?

**Comment by hktang** [comment]
I would defer this and limit user input to plain text as most submission systems do. Enabling formatting will create a lot of new issues we need to address...

**Comment by browncrowned** [comment]
Well noted. so all the additional formula/diagram, etc will be an attachment.
