### ISSUE TITLE
shortcut to "contact us"

### ISSUE THREAD

**Issue by browncrowned** [hktang/apnis#123]
While working on the full proposal, on the page, maybe we can provide a button that opens a new tab for contact us? In case proponent finds any issue, so he/she can contact us straight away?

**Comment by hktang** [comment]
There's a "Help" button on the top right corner that points to the Using APNIS Guide, would that be enough?

Also, started a help page about submitting fp,  https://apn.gitbooks.io/using-apnis/content/24-submitting-a-full-proposal.html .. how does that look? You can edit it too.. btw

**Comment by browncrowned** [comment]
Help button pointing to guide is okay. And mailto should be useful. So they can directly ask if they cant find any answer from the help.
