### ISSUE TITLE
insert symbols?

### ISSUE THREAD

**Issue by browncrowned** [hktang/apnis#124]
Is it possible for proponent to insert symbol into main text? like sigma, phi, and other formatting like subscript and superscript?

**Comment by hktang** [comment]
@browncrowned  I tend to prefer limiting user input to plain text only. Also, plain text has Unicode support so symbols like π, Δ etc, should be able to display correctly. 

Giving user access beyond plain text could lead to some security issues, and also some styling things we don't expect (like too many formats, large fonts etc). I also do believe most of the online submission like these do not offer styling options. So I would suggest we leave these fields as plaintext. What do you think?
