### ISSUE TITLE
submit button for the full proposal?

### ISSUE THREAD

**Issue by browncrowned** [hktang/apnis#129]
At the moment, not clear how it will look like after a proponent completed the full proposal. will there be Submit button like summary proposal later?

**Comment by hktang** [comment]
Right, this is clearly something missing. Just thinking, we don't need to enforce a deadline for this action, right? 

- [ ] Add FP submit button for applicants. 
- [ ] Add FP withdrawal button for applicants.

**Comment by browncrowned** [comment]
Nope. Just that when/if we will do the FP by APNIS then it will be available.

**Comment by hktang** [comment]
Shall we discourage people to withdraw their submission after they press the submit button?

This means, once submitted, cannot withdraw/return to draft state (unless admin sets the proposal to "draft").

**Comment by browncrowned** [comment]
agree! at the full proposal stage. should be stricter.
