### ISSUE TITLE
Improvement: more improvements before stage 2

### ISSUE THREAD

**Issue by hktang** [hktang/apnis#141]
- [x] 1. Add instructions on how to locate their proposal
- [x] 2. Revise the shortlist email preview -- change `first_name` to `last_name`.
- [x] 3. Add head of division to CC list.
- [x] 4. Change "pen edit" links to Buttons.
- [x] 5. In the FP form, provide information about maximum characters allowed. 
- [x] 6. In the "call setting" page, add file upload fields for general instructions and other files which will be placed before individual reviewer comments.
- [x] 7. Resolve labelling issue in call index: call should be *labelled* "active" from stages 1 through 3.
- [x] 8. Instruction/notification on the plain text submission only. Figure/formula/diagram/graph needs to be compiled as appendix and reference is to be provided in the main text.
- [x] 9. Enable PDF download for SP and FP.
- [x] 10. SP proposals should come from "Do Reply", instead of "No Reply".

**Comment by browncrowned** [comment]
- [ ] Instruction/notification on the plain text submission only. Figure/formula/diagram/graph needs to be compiled as appendix and reference is to be provided in the main text.

**Comment by hktang** [comment]
Moved "low-priority" ones and "future" ones to separate new issues.
