### ISSUE TITLE
Getting the guidelines in line with the form

### ISSUE THREAD

**Issue by browncrowned** [hktang/apnis#66]
The current guideline provides URL of the call which will bring the user to the call announcement & summary proposal form, specific to CAPaBLE or CRRP. While the current APNIS set up is that user can only see the call once they log in to APNIS. 

General announcement on APN website --> URL available will lead to where? APNIS or specific call announcement (form)?

**Comment by hktang** [comment]
Currently, it will lead to the public call page, if the user is registered and logged in. 

If not, they will be redirected to the login page.

Let's make the **public call page** world-accessible without login?
